repos:
  - repo: local
    hooks:
      - id: just-check-quality-commit
        name: just check-quality-commit
        entry: just check-quality-commit
        language: system
        pass_filenames: false
      - id: just-test-all-ci
        name: just test-all-ci
        entry: just test-all-ci
        language: system
        pass_filenames: false
